CLASS zcl_06_storage_896 DEFINITION INHERITING FROM zcl_05_PLAN_896
  PUBLIC

  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_06_storage_896 IMPLEMENTATION.
ENDCLASS.
