CLASS zcl_lab_23_company_896 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC
      GLOBAL FRIENDS zcl_lab_24_partner_896.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
    DATA capital TYPE f VALUE '125.542'.
ENDCLASS.



CLASS zcl_lab_23_company_896 IMPLEMENTATION.
ENDCLASS.
