CLASS zcl_lab_38_prod_price_896 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    DATA price TYPE i.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_lab_38_prod_price_896 IMPLEMENTATION.
ENDCLASS.
