CLASS zcl_lab_63_work_file_896 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES zif_lab_06_file_896.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_LAB_63_WORK_FILE_896 IMPLEMENTATION.


  METHOD zif_lab_06_file_896~get_file_type.
    rv_file_type = 'Work File'.
  ENDMETHOD.
ENDCLASS.
